substitutions:
  _NAME: nodeserver
  _REGION: us-central1

steps:
  #step 1
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_NAME:latest", "-t", "gcr.io/$PROJECT_ID/$_NAME:$COMMIT_SHA", "."]
  #step 2
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/$_NAME:latest"
      ]
  #step 3
  # Configure a kubeclt workspace for this project
  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_NAME
      - KUBECONFIG=/workspace/.kube/config
  #step 4
  - name: "gcr.io/$PROJECT_ID/helm"
    entrypoint: 'bash'
    args: ['-c', 'helm upgrade --install $_NAME chart/nodeserver']
    env:
      - KUBECONFIG=/workspace/.kube/config
      - CLOUDSDK_COMPUTE_ZONE=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_NAME
# push images to Google Container Registry with tags
images:
  [
    "gcr.io/$PROJECT_ID/$_NAME:$COMMIT_SHA",
    "gcr.io/$PROJECT_ID/$_NAME:latest",
  ]
