apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email }} # Update to yours
    privateKeySecretRef:
      name: {{ .Values.acme.secretACMEprivkey }}
    solvers:
    - http01:
        ingress:
            class: ingress-gce