apiVersion: networking.k8s.io/v1beta1
kind: "Ingress"
metadata:
  name: {{ .Values.ingress.nodeserver.name }}
  namespace: "default"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.nodeserver.globalStaticIP }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/websocket-services: "{{  .Chart.Name }}-service"
    nginx.org/websocket-services: "{{  .Chart.Name }}-service"
    cert-manager.io/cluster-issuer: {{ .Values.cert.issuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls: 
    - hosts:
      - {{ .Values.ingress.nodeserver.host }}
      secretName: {{ .Values.cert.secrectConfigMap }}
  rules:
  - host: {{ .Values.ingress.nodeserver.host }}
    http:
      paths:
      - path: {{ .Values.ingress.nodeserver.path }}
        backend:
          serviceName: "{{  .Chart.Name }}-service"
          servicePort: {{ .Values.service.port }}