apiVersion: v1
kind: Secret
metadata:
    name: dbpass
type: Opaque
data:
    password: {{ .Values.password.databasePassword | b64enc }}
    {{- range $key, $val := .Values.env.secret }}
    {{ $key }}: {{ $val | b64enc }}
    {{- end}}
