replicaCount: 2
revisionHistoryLimit: 1
image:
  repository: gcr.io/cloudkite-interviews-ali/nodeserver
  tag: latest
  pullPolicy: Always 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  readinessProbe: {}
  # Example (replace readinessProbe: {} with the following):
  readinessProbe:
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe: {}
  # Example (replace livenessProbe: {} with the following)::
  livenessProbe:
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 40
    periodSeconds: 10
service:
  name: Node
  type: NodePort
  servicePort: 3000
  port: 3000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
cert:
  issuer: letsencrypt-staging
  secrectConfigMap: cert-secret
ingress:
  nodeserver:
    name: nodeserver-ingress
    host: test.sarme.cyou
    path: /*
    globalStaticIP: nodeserverip
password:
  databasePassword: 123abc
env:
  env: 'production'
  secret:
    GRAPHQL_ADMIN_SECRET: "demo"
    AZURE_STORAGE_ACCOUNT_NAME: "demo"
    AZURE_ACCOUNT_ACCESS_KEY: "demo"
    AZURE_SERVICE_BUS_CONNECTION_STRING: "demo"
    KEYCLOAK_BASE_URL: "demo"
